graph exporter and inference code
deepdot-ai/models pull request #1
Opened 2018-06-02 22:42 UTC by ziyi-yang

@caihsiao @xiangxin-zhu

2018-06-02 22:51 UTC, xiangxin-zhu requested changes

2018-06-02 22:51 UTC, xiangxin-zhu commented on WORKSPACE
> +tensorflow_http_archive(
Please add a comment that the tensorflow version here must match the swift repo.

2018-06-02 22:51 UTC, xiangxin-zhu commented on WORKSPACE
> +# Abseil
Delete Abseil.

2018-06-02 22:51 UTC, xiangxin-zhu commented on WORKSPACE
> +http_archive(
Same here, please comment that the version must match that in swift.

2018-06-02 22:51 UTC, xiangxin-zhu commented on research/object_detection/inference_on_image.py
> +PATH_TO_TEST_IMAGES_DIR = '/home/xiangxin/Downloads/test_image/test'
remove line 67.

2018-06-02 22:51 UTC, xiangxin-zhu commented on research/object_detection/inference_on_image.py
> +#with detection_graph.as_default():
remove line 46-50?

2018-06-02 22:51 UTC, xiangxin-zhu commented on research/object_detection/inference_on_image.py
> +#MODEL_NAME = 'ssd_mobilenet_v1_coco_2017_11_17'
No MODEL_NAME is specified?

2018-06-03 00:42 UTC, ziyi-yang reviewed
Fixed path and cleaned.

2018-06-03 00:42 UTC, ziyi-yang commented on WORKSPACE
> +tensorflow_http_archive(
added.

2018-06-03 00:42 UTC, ziyi-yang commented on WORKSPACE
> +http_archive(
added.

2018-06-03 00:42 UTC, ziyi-yang commented on WORKSPACE
> +# Abseil
removed.

2018-06-03 00:42 UTC, ziyi-yang commented on research/object_detection/inference_on_image.py
> +PATH_TO_TEST_IMAGES_DIR = '/home/xiangxin/Downloads/test_image/test'
removed.

2018-06-03 00:42 UTC, ziyi-yang commented on research/object_detection/inference_on_image.py
> +#with detection_graph.as_default():
removed.

2018-06-03 00:42 UTC, ziyi-yang commented on research/object_detection/inference_on_image.py
> +#MODEL_NAME = 'ssd_mobilenet_v1_coco_2017_11_17'
User-specified path.

2018-06-03 01:16 UTC, xiangxin-zhu approved these changes

2018-06-03 01:17 UTC, merged